#!/usr/bin/env php
<?php
require 'vendor/pear/Universal/ClassLoader/BasePathClassLoader.php';
$classLoader = new \Universal\ClassLoader\BasePathClassLoader(array( 
    'src', 'vendor/pear' ));
$classLoader->useIncludePath(true);
$classLoader->register();

$app = new \MiniPear\Console;
$app->run( $argv );
